//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSS.Image.DownloadImageCompanyServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ID { get; set; }
        public Nullable<long> ClassificationID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Warranty { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<long> Company { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Promotion { get; set; }
        public string Summary { get; set; }
        public string ProductContent { get; set; }
        public string Name { get; set; }
        public string DetailUrl { get; set; }
        public string ImageUrls { get; set; }
        public string NameFT { get; set; }
        public Nullable<bool> Valid { get; set; }
        public Nullable<System.DateTime> LastPriceChange { get; set; }
        public Nullable<int> PriceChange { get; set; }
        public Nullable<bool> IsNews { get; set; }
        public Nullable<long> HashName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ContentFT { get; set; }
        public Nullable<byte> DownloadError { get; set; }
        public Nullable<int> ImageWidth { get; set; }
        public Nullable<int> ImageHeight { get; set; }
        public Nullable<int> CategorySTT { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> PriceChangeWeek { get; set; }
        public Nullable<int> AddPosition { get; set; }
        public string VATInfo { get; set; }
        public string PromotionInfo { get; set; }
        public Nullable<bool> IsBlackList { get; set; }
        public Nullable<int> OriginPrice { get; set; }
        public string DeliveryInfo { get; set; }
        public Nullable<bool> IsDeal { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<System.DateTime> StartDeal { get; set; }
        public Nullable<System.DateTime> EndDeal { get; set; }
        public Nullable<int> InStock { get; set; }
        public Nullable<int> VATStatus { get; set; }
        public Nullable<long> ProductDuplicate { get; set; }
        public Nullable<byte> CountFail { get; set; }
        public Nullable<int> AdsScore { get; set; }
        public Nullable<System.DateTime> CreateDate_AddPosition { get; set; }
    }
}
