//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QT.Users.ServiceCoreApplication {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCoreApplication.ICoreApplication")]
    public interface ICoreApplication {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoreApplication/DoWork", ReplyAction="http://tempuri.org/ICoreApplication/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoreApplication/GetConnection", ReplyAction="http://tempuri.org/ICoreApplication/GetConnectionResponse")]
        byte[] GetConnection(string User, string Pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoreApplication/GetConnectionCrawler", ReplyAction="http://tempuri.org/ICoreApplication/GetConnectionCrawlerResponse")]
        byte[] GetConnectionCrawler(string User, string Pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoreApplicationChannel : QT.Users.ServiceCoreApplication.ICoreApplication, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreApplicationClient : System.ServiceModel.ClientBase<QT.Users.ServiceCoreApplication.ICoreApplication>, QT.Users.ServiceCoreApplication.ICoreApplication {
        
        public CoreApplicationClient() {
        }
        
        public CoreApplicationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoreApplicationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreApplicationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreApplicationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public byte[] GetConnection(string User, string Pass) {
            return base.Channel.GetConnection(User, Pass);
        }
        
        public byte[] GetConnectionCrawler(string User, string Pass) {
            return base.Channel.GetConnectionCrawler(User, Pass);
        }
    }
}
