//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QT.Moduls.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.205.94,1452;Initial Catalog=QTCrawler;Persist Security Info=Tr" +
            "ue;User ID=qt_vn;Password=@F4sJ=l9/ryJt9MT")]
        public string QTCrawlerConnectionString {
            get {
                return ((string)(this["QTCrawlerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.205.94,1452;Initial Catalog=NCWebCrawler;Persist Security Info" +
            "=True;User ID=Gabiz;Password=trungchem!@21")]
        public string ReaderDataConnectionString {
            get {
                return ((string)(this["ReaderDataConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=42.112.28.93;Initial Catalog=QT_2;Persist Security Info=True;User ID=" +
            "wss_price;Password=HzlRt4$$axzG-*UlpuL2gYDu;Connect Timeout=200")]
        public string QTConnectionString {
            get {
                return ((string)(this["QTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=42.112.17.186;Initial Catalog=ReviewsCMS;Persist Security Info=True;U" +
            "ser ID=qt_rv;Password=@F4sJ=l9/ryJt9MT")]
        public string ReviewsConnectionString {
            get {
                return ((string)(this["ReviewsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-6ICNIQVFE0A;Initial Catalog=SaleNews;Integrated Security=True")]
        public string SaleNewsConnectionString {
            get {
                return ((string)(this["SaleNewsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-6ICNIQVFE0A;Initial Catalog=SaleNews;User ID=sa;Password=123")]
        public string SaleNewsConnectionString1 {
            get {
                return ((string)(this["SaleNewsConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=183.91.14.82;Initial Catalog=QT_2;Persist Security Info=True;User ID=" +
            "qt_crawler;Connect Timeout=5000")]
        public string QT_2ConnectionString {
            get {
                return ((string)(this["QT_2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=42.112.28.93;Initial Catalog=QT_2;User ID=wss_product;Password=HzlRt4" +
            "$$axzG-*UlpuL2gYDu")]
        public string QT_2ConnectionString1 {
            get {
                return ((string)(this["QT_2ConnectionString1"]));
            }
        }
    }
}
