//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateSolrTools {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.205.94,1452;Initial Catalog=QTCrawler;Persist Security Info=Tr" +
            "ue;User ID=qt_vn;Password=@F4sJ=l9/ryJt9MT")]
        public string QTCrawlerConnectionString {
            get {
                return ((string)(this["QTCrawlerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.205.94,1452;Initial Catalog=NCWebCrawler;Persist Security Info" +
            "=True;User ID=Gabiz;Password=trungchem!@21")]
        public string ReaderDataConnectionString {
            get {
                return ((string)(this["ReaderDataConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.205.94,1455;Initial Catalog=QT_2;Persist Security Info=True;Us" +
            "er ID=qt_vn;Password=@F4sJ=l9/ryJt9MT")]
        public string QTConnectionString {
            get {
                return ((string)(this["QTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.205.94,1455;Initial Catalog=QT_User;Persist Security Info=True" +
            ";User ID=qt_vn;Password=@F4sJ=l9/ryJt9MT")]
        public string UserConnectionString {
            get {
                return ((string)(this["UserConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.205.94,1455;Initial Catalog=QT_User;Persist Security Info=True" +
            ";User ID=qt_vn;Password=@F4sJ=l9/ryJt9MT")]
        public string ReviewsConnectionString {
            get {
                return ((string)(this["ReviewsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=118.70.205.94,1455;Initial Catalog=QT_2;Persist Security Info=True;Us" +
            "er ID=qt_vn;Password=@F4sJ=l9/ryJt9MT")]
        public string QT_2ConnectionString {
            get {
                return ((string)(this["QT_2ConnectionString"]));
            }
        }
    }
}
