using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using QT.Entities;
using QT.Entities.Data;
using QT.Moduls.CrawlerProduct;
using StackExchange.Redis;
using Websosanh.Core.Drivers.Redis;
using System.Data.SqlClient;

namespace WSS.Core.Crawler
{
    public  class WorkerExportCategory
    {
        private log4net.ILog log = log4net.LogManager.GetLogger(typeof(WorkerExportCategory));
        public void Start()
        {
            string data = @"alobuy.vn
haianh.vn
knic.vn
lingo.vn
telo.vn
manhnguyen.com.vn
sieuthithanhcong.com
yes24.vn
dtcvietnam.com.vn
huongshop.vn
thegioikts.com
khoedepeva24h.com
familydeal.vn
kidsplaza.vn
lingo.vn
shoptuancua.com
bkc.vn
alobuy.vn
dienmaysaigon.com
hanghoachatluong.com
trevang.vn
saigonmusical.com.vn
cellphones.com.vn
kimnganhanoi.vn
congtyphuongnam.vn
evadeal.vn
sieuthithanhcong.com
f5fashion.vn
thoitrangxitin.com
muatot.vn
unigolf.vn
ghettre.com
doibanthan.vn
quatructuyen.com
telo.vn
dienthoaila.com
mykim.vn
yes24.vn
dongho24h.com
suabim.vn
muagiamgia.net
chuyengiasi.vn
bebeland.com.vn
lunibaby.com/
ngocanhshop.com.vn
apalife.com
maytinhbanggiasi.com
jotunshop.vn
xedaponline.vn
Ecare.vn
camerahoanglam.net
streetstyle.vn
bangiatot.vn
Dienmayhikaru.com
cucvip.vn
babimart.com
365mobile.vn
bepquangvinh.com
babo.vn
maimua.com
dogiadung.net.vn
anchau.vn
chamsocbesosinh.com
babylovevn.com
sua.vn
tickmua.com
thegioipinsac.vn
smartphonestore.vn
bibomart.com.vn
memoryzone.com.vn/
dochoiaz.vn
banhtrungthuthuhuong.net
quatangsumo.com
hoavoanmytho.com
thenhominhhang.com
banmaylanh.com
audionghiathuy.com
deal1.vn
androidgiare.vn
deltamevn.com
vienthongnam.com
muathuoctot.com
thegioisi.com
daugoichinhhang.com
suboy.vn
sphoto.vn
manhnguyen.com.vn
dienmaythienphuc.vn
batlua.vn
cameraminhanh.com
vndeal.net
giaiphapmaytinhtien.com
thaovinhvnt.com
haily.vn
laptoptragop.com.vn
thethaore.com
giaydabanh.com
sieumuanhanh.com
thegioikts.com
mkjsc.com.vn
noithatmiennam.com
digiphone.com.vn
azaudio.vn
tienloi24h.com.vn
noithatnhapkhau.net.vn
hongyen.vn
kdeal.vn
matkinhnamquang.com
chuthi.vn
bigshop.vn
maylocnuockangaroo.vn
kangaroohanoi.vn
thietbivesinhviet.com
giaphucomputer.com
dodiengiare.vn
shopbevame.com
kimnganhanoi.vn
babycuatoi.vn
fastmarket.vn
xedapkhaisang.com
uudaigia.com
thoitrang79.com
thaivinhphukien.com
dochoididong.com
vienthinh.vn
sacmauchobe.com
halobuy.vn
giadinhmart.vn
lamdep365.com.vn
dientulinhanh.com
ketnoitieudung.vn
nhanhmua.vn
lottedatviet.vn
mualachuan.com
nasa.vn
gangnammobile.vn
alobuy.vn
zoombuy.com.vn
shopmeyeucon.com
laptopchinhhang.com
banhandamchobe.net
vietlongbaby.vn
phunu24h.com.vn
giavu.vn
dungcuykhoabachhue.com
cycybon.com
dienmayduclong.vn
sola.vn
vitinhhoaibao.com
loagiare.com
dealhotvn.com
deal1.vn
okbuy.vn
cucvip.vn
domy.vn
noithatmiennam.com
brandon.com.vn
quatpanasonic.com.vn
quattranden.net.vn
anchau.vn
phunu24h.com.vn
bepminhha.com
goodlink.vn
babymart.vn
laptopprocom.vn
nhathuocviet.vn
http://huyhoang.vn/
hptvn.com
hongminhbaby.vn
www.dienmaytantien.vn
ytecaocap.com
picnictoy.vn
dienmayvico.com
thethaore.com
Vohoang.vn
thenhominhhang.com
caganu.com
phuquangkts.vn
kay.vn
thegioitragop.vn
dasangdangxinh.vn
tga.vn
ledvina999.vn
nguyenkim.com
songlongmedia.com
webhangnhat.com
duongmonglinh.com
saha.vn
rawshop.vn
nguyenhoamobile.com
playmobile.vn
shopnhaxinh.com
thegioididongsamsung.com
sieuthidienmaychinhhang.vn
bichngocmobile.com
laptopvip.vn
lemonshop.com.vn
baongoclaptop.com
vienthongthanhpho.vn
usamua.com
otb.vn
ytehoanggia.com
laptop3mien.vn
dienlanhnasan.com
xachtaynhat.com.vn
thoitrangxitin.com
hongdungsport.com
Shopsieure.com
nhaccuquythanh.com
hanoilab.com.vn
thegioilinhphukien.vn
dienthoaire.vn
kimphu.vn
dienmayhoanghai.vn
myphamhoaithu.com
khoevadepeva.com
phukienthoigian.com
u100.vn
amuasam.com
huylongphat.com.vn
ketsatson.com
doibanthan.vn
shopbabyfun.com.vn
tula.vn
xechobe.com.vn
htt.com.vn
muatot.vn
thegioithethao360.vn
haduong.vn
itech365.vn
htt.com.vn
vienthongmoi.com
panasonic-tphcm.com
kingshop.vn
thegioithethao360.vn
thethaore.com
chotinhcuaboo.com
homeoffice.com.vn
dongho24h.com
lunibaby.com/
eco-mart.com.vn
kingshop.vn
baoholaodongthienbang.com
deal1.vn
chodeal24h.vn
hongnguyensc.com.vn
ytecaocap.com
goodlink.vn
okbuy.vn
baoholaodongthienbang.com
hoangphatvn.vn
vanphatmobile.com.vn
vitinhbaoan.com
thegioikts.com
dienmayhikaru.com
hoaphathanoi.vn
bigmua.com
thenhominhhang.com
mayanhonline.com
afe.vn
Sieuthihangphap.com
hot.vn
thanhloansport.com.vn
giaysanco.com
happyworld.vn
batluadocdao.com
goldenhouse.com.vn
dealvip.vn
haolamshop.com
Thietbiytethuchuyen.com
Tanlongcamera.com
depeva.com
nmobile.vn
bigmua.com
lequanmobile.com
ianker.vn
tiengiaphat.vn
shopthegioihangdoc.com
f5c.vn
nhasachphuongnam.com
longbinh.com.vn
thegioilinhphukien.vn
dienmaykhanghuy.vn
tickmua.com
bengo.vn
iservice.vn
okbuy.vn
bachkhoashop.com
bepquangvinh.com
dongho24h.com
alomua360.com
umove.vn
fahasa.com
sieuthiphongphu.com
leofone.vn
chinhnhan.vn
sieumuanhanh.com
mediamart.vn
didongviet.vn
phucanh.vn
dienmaytruongviet.vn
thaovinhvnt.com
banmaylanh.com
bibomart.com.vn
bichha.vn
bosomivietnam.com
deal1.vn
digiphone.com.vn
manhnguyen.com.vn
sieuthidienmaymiennam.com
banhangusa.com
thethaore.com
microthuam.com
donghobcat.com
ytecaocap.com
chiaki.vn
anchau.vn
anchau.vn
adayroi.com
adayroi.com
chuthi.vn
maivangdatviet.com
kizomart.com.vn
thegioipinsac.vn
okbuy.vn
phukiengiare.com
anhduongmobile.com.vn
xedapkhaisang.com
vinbarista.com
yeucon247.com
chamsocbesosinh.com
anhduongmobile.com.vn
muadienthoai.vn
kdeal.vn
toilav.com
linhkiendidong.net
giaydabanh.com
laptopdell.vn
babylovevn.com
gangnammobile.vn
sacmauchobe.com
youshopping.vn
catlaser-cncgiare.com
dienmaycholon.vn
domy.vn
sola.vn
nhanhmua.vn
tech4you.vn
thegioipinsac.vn
trangtuan.com
dgcameras.vn
vntvbox.vn
kay.vn
loagiare.com
dochoididong.com
phunu24h.com.vn
cnttshop.vn
vinhtranmobile.com
okbuy.vn
thenhominhhang.com
cucvip.vn
goodlink.vn
dienmayduclong.vn
phunu24h.com.vn
sieumuanhanh.com
vienthongthanhpho.vn
bigshop.vn
hongminhbaby.vn
songlongmedia.com
vimax.vn
mykim.vn
ngocanhshop.com.vn
telo.vn
kieusashop.vn
applepro.vn
pinsacdidong.net
otb.vn
dienmay247.com
itshophanoi.vn
ytehoanggia.com
laptopvip.vn
dienmaybinhminh.com
shopmebill.com
vuahatchia.com
vohoang.vn
dienlanhminhkhoa.vn
takara.vn (mikaro.vn)
webhangnhat.com
dienmay247.com
tech4you.vn
shopbabyfun.com.vn
suabim.vn
suckhoexanh.vn
dienmayso8.com
myphamhoangdung.com
vientammobile.com
bibomart.com.vn
huyphu.com
myphamtocthunhung.com
linhkiendidong.net
thenhominhhang.com
yes24.vn
huyphu.com
Dienmayhoanghai.vn
Dienmayquanghanh.com
thegioiquattran.com.vn
dienmaycholon.vn
ali-vn.com
haduong.vn
memoryzone.com.vn
lunibaby.com
bige.vn
thoitrangtichtac.com
4tech.vn
nerfviet.com
Xuannhi.co
hoangphatvn.vn
sieuthibepga.net
deal1.vn
bachlong.vn
Dienmayquanghanh.com
manhnguyen.com.vn
sieuthidienmaychinhhang.vn
suachobeyeu.vn
chodeal24h.vn
sieumuanhanh.com
xachtaynhat.com.vn
thaonhien.com.vn
taembe.com
cungmua.com
Anphatpc.com.vn
tga.vn
www.phukienminhhieu.com
saha.vn
dienmaythudo.com
Thegioitu.com
dienmaycuongdat.com
dongho24h.com
fam.vn
Bigmua.com
myky.com.vn
Lanhuongmart.vn
maycaphenhapkhau.com
thegioilinhphukien.vn
www.thietbigames.com
www.microthuam.com
Shoptuancua.com
www.phammykim.vn
maytinhkimlong.com
tga.vn
Ora.life
www.vitinhvominh.com
www.dienmaykimnga.com
www.noithatmiennam.com
thegioiboardgame.vn
www.alovendor.com
www.evadeeva24h.com
www.fptshop.com.vn
www.banmaylanh.com
www.Aothun24h.vn
www.dienmaygiakhang.vn
www.myphamhanquocq8.com
http://dogiadung.net.vn/
www.imua.com.vn
www.chuyencungcap.com
www.giadunghanquoc.net
www.amazona.vn
kholaptopthaihoa.com
F5c.vn
Dnmart.vn
Hanoilab.com.vn
www.deal1.vn
goldenhouse.com.vn
avishop.vn
Giatot24h.net
www.giamcanngoai.com
www.daiphatloc.com.vn
tamphatshop.com
www.topazshop.vn
www.12mua.com
www.quatangme.com
www.thenhominhhang.com
www.mevabe123.vn
Kimnganhanoi.vn
www.dungcuykhoabachhue.com
www.topazshop.vn
dientulinhanh.com
www.sieuthiyte.com.vn
www.nhanhmua.vn
www.fptshop.com.vn
Babimart.com
www.dienmaycholon.vn
www.myphamus.vn
dienmaychicuong.com
www.thuanthe.com
www.viettablet.com
mangxanh.vn
dochoididong.com
www.dienmaycholon.vn
cucvip.vn
manhnguyen.com.vn
www.myphamhanquochcm.com
www.okbuy.vn
www.vienthongmoi.com
www.dienlanh50.com
Quattranden.net.vn
Quatpanasonic.com.vn
kienquoc.net
yteanhtu.com
www.xedapkhaisang.com
www.dienmayantam.vn
scj.vn
www.mac24h.vn
www.usamua.com
www.babymart.vn
www.sieumuanhanh.com
www.bepkhanhvy.vn
www.muadonhanh.com
www.camera4k.vn
www.thoitrangxitin.com
mangxanh.vn
thegioi2tech.com
vitinhvominh.com
babymua.com
etoy.vn
phucanh.vn
139.vn
loagiare.com
deal1.vn
shopmebill.com
dienmaynhatban.vn
phukien.com.vn
dientungocminh.vn
www.babymart.vn
quattranden.com.vn
hongminhbaby.vn
dienmayduclong.vn
giahotnhat.com
chichishop.com.vn
yteanhtu.com
myphamsino.com
mediamart.vn
onlinekangaroo.vn
vuaphukienso.com
dienmaytanbinh.vn
picnictoy.vn
dohieuchobe.vn
goodlink.vn
evamua.vn
aloday.com.vn
binhsuangoai.com
obabyshop.vn
bigshop.vn
cohoimua.com
alobuy.vn
babieskids.vn
thivi.vn
laptopusa.com.vn
ytehoanggia.com
songlongmedia.com
laptopvip.vn
dienmayso8.com
dodiengiare.vn
fastmarket.vn
hoaphathanoi.vn
mobilepro.com.vn
zemzemshop.com
shinperfume.com
rawshop.vn
myphamtocthunhung.com
phukienrenhat.net
vuhoangtelecom.vn
chotinhcuaboo.com
babydeal.vn
fahasa.com
quakhuyenmaivn.com
dochoilego.vn
thegioicuabe.net
vinared.vn
thegioisua.us
decalsaigon.com
cholonsaigon.vn
giadungsoctho.com
aloola.vn
taphoahangmy.com
inmstore.vn
zeal.vn
mshopcamera.com
dienlanhsieure.com
metieulong.com
fahasa.com
upschinhhang.com
kimnganhanoi.vn
sonsaoviet.com
24hstore.vn
dailydienmay.vn
xaumasoc.com
alomevabe.vn
mua99.vn
wowmart.vn
dienlanhduykhoa.com
shop79.vn
shopchoang.vn
ketnoitieudung.vn
panodo.vn
jackyjeans.com
nvfashion.vn
theauthenticwatch.com
songnhac.com.vn
dogotoiyeu.com.vn
aventkid.com
adayroi.com
quatpanasonic.com.vn
quattranden.net.vn
deal1.vn
kidsfami.com
sumall.vn
alconi.vn
bacsidalieu24h.vn
sunnybaby.vn
thietbiytethuchuyen.com
shopmaika.com
thuocbonhatban.com
";
            QT.Entities.Server.ConnectionString = ConfigCrawler.ConnectProduct;
            ProductAdapter productAdapter = new ProductAdapter(new SqlDb(QT.Entities.Server.ConnectionString));
            var lstDomain = data.Split(Common.arSplitToList, StringSplitOptions.RemoveEmptyEntries);

            int countDomain = 0;
            IDatabase db = RedisManager.GetRedisServer("redisConfigCat").GetDatabase(0);
            foreach (var domain in lstDomain)
            {
                countDomain++;
                 List<Tuple<long, long>> lstCat = new List<Tuple<long, long>>();
                long companyId = productAdapter.GetCompanyIDFromDomain(domain.Trim());
                var ProductIds = productAdapter.GetAllProductIDsByCompany(companyId).ToList();

                foreach (var subLstProductIds in Common.SplitArray<long>(ProductIds, 500))
                {

                    RedisKey[] arRedisKeys = new RedisKey[subLstProductIds.Count];
                    for (int i = 0; i < subLstProductIds.Count; i++)
                        arRedisKeys[i] = "PRODUCT_CATID:" + subLstProductIds[i].ToString();
                    RedisValue[] redisValue = db.StringGet(arRedisKeys, CommandFlags.HighPriority);
                    for (int i = 0; i < redisValue.Length; i++)
                    {
                        if (redisValue[i].HasValue)
                        {
                            lstCat.Add(new Tuple<long, long>(ProductIds[i], Convert.ToInt64(redisValue[i])));
                        }
                    }

                    if (lstCat.Count > 0)
                    {
                        List<string> lst = new List<string>();
                        for (int i = 0; i < lstCat.Count; i++)
                        {
                            lst.Add(string.Format("Insert Into Product_Category (Product_Id, Category_Id) Values ({0}, {1})", lstCat[i].Item1, lstCat[i].Item2));
                        }

                        bool bOK = productAdapter.GetSqlDb().RunQuery(string.Join(";", lst), CommandType.Text, null);
                        Console.WriteLine(bOK);
                        lstCat.Clear();
                    }
                }

                log.InfoFormat("Success for domain {0} {1}/{2}", domain, countDomain, lstDomain.Count());
            }
        }
    }
}
