//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSS.Tools.MerchantRankByWebsosanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantScore
    {
        public long MerchantId { get; set; }
        public string MerchantWebsite { set; get; }
        public Nullable<int> ScoreNumberProduct1 { get; set; }
        public Nullable<int> ScoreStore1 { get; set; }
        public Nullable<double> ScoreTraffic1 { get; set; }
        public Nullable<int> ScoreAdvertisementPR1 { get; set; }
        public Nullable<int> ScoreScandal1 { get; set; }
        public Nullable<double> TotalPart1 { get; set; }
        public Nullable<int> ScoreAddressStore2 { get; set; }
        public Nullable<int> ScorePhoneNumberAvaiable2 { get; set; }
        public Nullable<int> ScoreCustomerServices2 { get; set; }
        public Nullable<double> TotalPart2 { get; set; }
        public Nullable<int> ScoreProductInformation3 { get; set; }
        public Nullable<int> ScoreWebsosanhRate3 { get; set; }
        public Nullable<int> ScoreGoogleRate3 { get; set; }
        public Nullable<int> ScoreRateWebsite3 { get; set; }
        public Nullable<double> TotalPart3 { get; set; }
        public Nullable<int> ScoreStatusProduct4 { get; set; }
        public Nullable<int> ScoreSignContract5 { get; set; }
        public Nullable<int> ScoreResignContract5 { get; set; }
        public Nullable<int> ScorePotential5 { get; set; }
        public Nullable<int> ScoreSales5 { get; set; }
        public Nullable<double> TotalPart5 { get; set; }
        public double Score { get; set; }
    }
}
